export interface User {
    id: number,
    name: string,
    lastName: string,
    maidenName?: string,
    gender: string,
    phone?: string,
    photoUrl: string,
    specialization: string,
    state: string,
    country: string,
    registrationDate: Date,
    lastConnection: Date,
    notifications: boolean,
}